In [4]:
# Now we are gonna play with Numbers!
import numpy
help(numpy.genfromtxt)    # numpy is a Python library and genfromtxt is a Python fuunction.


Help on function genfromtxt in module numpy:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+,-./:;<=>?@[\\]^{|}~", replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes', *, ndmin=0, like=None)
    Load data from a text file, with missing values handled as specified.

    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.

    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is ``.gz`` or ``.bz2``, the file is first decompressed. Note
        that generators must return bytes

In [68]:
# Instead of readlines() function, we are going to use numpy.genfromtxt function here.

import os
import numpy

distance_file = os.path.join('CMS Workshp (MolSSI data)' , 'distance_data_headers.csv')
distance_data = numpy.genfromtxt(fname = distance_file, delimiter = ',' , dtype = 'unicode')
print(distance_data)

# Here fname is either the file or filepath, ',' should be used as a delimiter for a CSV file and data
# type should be unicode (combination of string and float type).

[['Frame' 'THR4_ATP' 'THR4_ASP' 'TYR6_ATP' 'TYR6_ASP']
 ['1' '8.9542' '5.8024' '11.5478' '9.9557']
 ['2' '8.6181' '6.0942' '13.9594' '11.6945']
 ...
 ['9998' '8.6625' '7.7306' '9.5469' '10.3063']
 ['9999' '9.2456' '7.8886' '9.8151' '10.7564']
 ['10000' '8.8135' '7.917' '9.9517' '10.7848']]


In [18]:
# The first row of data is headings for our columns, and will need to be stored as 'strings', 
# whereas all the rest of the data is numerical and will need to be stored as 'floats'.

header = distance_data[0]
print(header)

print('')

data = distance_data[1:]
print(data)

['Frame' 'THR4_ATP' 'THR4_ASP' 'TYR6_ATP' 'TYR6_ASP']

[['1' '8.9542' '5.8024' '11.5478' '9.9557']
 ['2' '8.6181' '6.0942' '13.9594' '11.6945']
 ['3' '9.0066' '6.0637' '13.0924' '11.3043']
 ...
 ['9998' '8.6625' '7.7306' '9.5469' '10.3063']
 ['9999' '9.2456' '7.8886' '9.8151' '10.7564']
 ['10000' '8.8135' '7.917' '9.9517' '10.7848']]


In [38]:
# As we know that all the data from a txt or any file is saved as string type. Although, the numbers are
# supposed to be float, but they are saved as strings in the file. 
# To change their type to float for the entire data:

# data = data.astype(numpy.float)
# print(data)

import numpy

data = data.astype(numpy.float64)
print(data)

[[1.00000e+00 8.95420e+00 5.80240e+00 1.15478e+01 9.95570e+00]
 [2.00000e+00 8.61810e+00 6.09420e+00 1.39594e+01 1.16945e+01]
 [3.00000e+00 9.00660e+00 6.06370e+00 1.30924e+01 1.13043e+01]
 ...
 [9.99800e+03 8.66250e+00 7.73060e+00 9.54690e+00 1.03063e+01]
 [9.99900e+03 9.24560e+00 7.88860e+00 9.81510e+00 1.07564e+01]
 [1.00000e+04 8.81350e+00 7.91700e+00 9.95170e+00 1.07848e+01]]


In [48]:
# Now to get any particular element of the array

data[0,0]
data[0,1]
data[1,0]
print(data[0,0], data[0,1], data[1,0])

print(data[0,0])
print(data[0,1])
print(data[1,0])

1.0 8.9542 2.0
1.0
8.9542
2.0


In [52]:
# To print first 10 rows (0,1,2,3,4,5,6,7,8,9)and first three columns (0,1,2)
small_data = data[0:10 , 0:3]
print(small_data)

[[ 1.      8.9542  5.8024]
 [ 2.      8.6181  6.0942]
 [ 3.      9.0066  6.0637]
 [ 4.      9.2002  6.0227]
 [ 5.      9.1294  5.9365]
 [ 6.      9.0462  6.2553]
 [ 7.      8.8657  5.9186]
 [ 8.      9.3256  6.2351]
 [ 9.      9.4184  6.1993]
 [10.      9.06    6.0478]]


In [60]:
print(small_data[5,:])
print('')
print(small_data[:,1:])

[6.     9.0462 6.2553]

[[8.9542 5.8024]
 [8.6181 6.0942]
 [9.0066 6.0637]
 [9.2002 6.0227]
 [9.1294 5.9365]
 [9.0462 6.2553]
 [8.8657 5.9186]
 [9.3256 6.2351]
 [9.4184 6.1993]
 [9.06   6.0478]]


In [74]:
# To get the average of distance data

THR4_ATP = data[:,1]
print(THR4_ATP)
THR4_ATP_avg = numpy.mean(THR4_ATP)
print(THR4_ATP_avg)


[8.9542 8.6181 9.0066 ... 8.6625 9.2456 8.8135]
10.876950930000001


In [84]:
# To get the number of columns in each row. We know that every row (from 1 to 10,000) has 5 columns, and
# counting number of columns for one row is the same of all rows:

column_num = len (data[0,:])
print(column_num)

5


In [264]:
# To take the average of each column, we use the for loop.
# for this case, we already know "header" and "data" from our data. If not, then we have to specify it:
header = distance_data[0]     # distance_data is string, only having lists (1st 2nd 3rd and all)
data = distance_data[1:]      # same as above
data = data.astype(numpy.float64)

column_num = len (data[0,:])

for i in range(1, column_num):     # Here we assigned i to all columns and defined range from 1 to i
    #print(i)
    each_column = data[:,i]             # We defined each column as a list of all rows and column i (1 to 5)
    each_col_avg = numpy.mean(each_column)
    #print(col_avg)
    #print(header[i])
    print(F' Avg for {header[i]} : {each_col_avg}')

# NOTE THAT in the range, we specified the range from 1 to column_num, so i will be counted from 2nd col
# to the last column (we do not need to include the first column, as it is just a count of data).


 Avg for THR4_ATP : 10.876950930000001
 Avg for THR4_ASP : 7.342344959999999
 Avg for TYR6_ATP : 11.209791329999998
 Avg for TYR6_ASP : 10.9934435


In [198]:
# Let's calculate the bond length for O-O, O-H1, O-H2, H1-O, H1-H1, H1-H2, H2-O, H2-H1, H2-H2
# bond_len = sqrt ( (x2−x1)2+(y2−y1)2+(z2−z1)2 ) for xyz coordinates

import os
import numpy

xyz_file_path = os.path.join('CMS Workshp (MolSSI data)' , 'water.xyz')
xyz_file = numpy.genfromtxt(fname = xyz_file_path , delimiter = ',' , dtype = 'unicode')
# print(xyz_file)
xyz_file = xyz_file[2:]       # I could have also used skip_header = 2 to remove first 2 rows.
print(xyz_file)

# This is not printing each element as a sperate string, as I specified delimiter = , while there is no ,
# in our file. So, python takes whole row as an array.
# I can't specify delimiter = None, as then it expects the number of columns in all rows to match. 
# Since our .xyz file has inconsistent formatting in the first two lines compared to the data rows, 
# numpy.genfromtxt raises a ValueError.


['O        0.000000     -0.007156      0.965491'
 'H1      -0.000000      0.001486     -0.003471'
 'H2       0.000000      0.931026      1.207929']


In [272]:
# Let's calculate the bond length for O-O, O-H1, O-H2, H1-O, H1-H1, H1-H2, H2-O, H2-H1, H2-H2
# bond_len = sqrt ( (x2−x1)2+(y2−y1)2+(z2−z1)2 ) for xyz coordinates
# To avoid specifying delimiter, we can use the skip_header argument to skip the first two rows and 
# avoid processing lines that don't match the data structure.

import numpy
import os

xyz_file_path = os.path.join('CMS Workshp (MolSSI data)', 'water.xyz')
xyz_file = numpy.genfromtxt(fname = xyz_file_path, skip_header=2,  dtype='unicode')  
#print(xyz_file)     

molecule = xyz_file[:,0]                           # These are our molecules (as string type)
print(molecule)
coordinates = xyz_file[:,1:]                       # These are our xyz coordinates (as string type)
coordinates = coordinates.astype(numpy.float64)    # These are our xyz coordinates (as float type)
print(coordinates)

# now we will split the columns and assign i to each column
col_num = len(coordinates[0,:])
print(col_num)
print('')

for i_1 in range(0, col_num):
    for i_2 in range(0, col_num):
        x_distances = coordinates[i_1,0] - coordinates[i_2,0]   
# i_1 / i_2 are just numbers varying from 1-3. So this command will vary row from 1 to 3 but for 1st col
        y_distances = coordinates[i_1,1] - coordinates[i_2,1]   
        z_distances = coordinates[i_1,2] - coordinates[i_2,2]
        bond_len = numpy.sqrt(x_distances**2 + y_distances**2 + z_distances**2)
        #print(bond_len)
        

# NOTE THAT in the range, we specified the range from 0 to column_num, so i will be counted from 1st col
# to the last column (here we need to include the first column, unlike the previous case).

# Now which bond length belongs to which data? The pattern based on above code should be 
# O-O, H1-O, H2-O for variable row and 1st column
# O-H1, H1-H1, H2-H1 for variable row and 2nd column
# O-H2, H1-H2, H2-H2 for variable row and 3rd column

        print(F'{molecule[i_1]} to {molecule[i_2]}:' , bond_len) 
        

['O' 'H1' 'H2']
[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]
3

O to O: 0.0
O to H1: 0.9690005374652793
O to H2: 0.9690003348647513
H1 to O: 0.9690005374652793
H1 to H1: 0.0
H1 to H2: 1.52693633514957
H2 to O: 0.9690003348647513
H2 to H1: 1.52693633514957
H2 to H2: 0.0


In [304]:
# Modify your code to only print the atoms that are actually bonded to each other.
# We Use a distance cutoff of 1.5 angstroms to define a bond (that is, if the bond length is less/equal 
# to 1.5 angstroms, or greater than 0, then consider the atoms are bonded).

import numpy
import os

xyz_file_path = os.path.join('CMS Workshp (MolSSI data)', 'water.xyz')
xyz_file = numpy.genfromtxt(fname = xyz_file_path, skip_header=2,  dtype='unicode')  
#print(xyz_file)     

molecule = xyz_file[:,0]                           # These are our molecules (as string type)
print(molecule)
coordinates = xyz_file[:,1:]                       # These are our xyz coordinates (as string type)
coordinates = coordinates.astype(numpy.float64)    # These are our xyz coordinates (as float type)
print(coordinates)

# now we will split the columns and assign i to each column
col_num = len(coordinates[0,:])       
print(col_num)
print('')

for i_1 in range(0, col_num):               # We could have said range(0,3), but to generlaize the code
    for i_2 in range(0, col_num):
        x_distances = coordinates[i_1,0] - coordinates[i_2,0]   
# i_1 / i_2 are just numbers varying from 1-3. So this command will vary row from 1 to 3 but for 1st col
        y_distances = coordinates[i_1,1] - coordinates[i_2,1]   
        z_distances = coordinates[i_1,2] - coordinates[i_2,2]
        bond_len = numpy.sqrt(x_distances**2 + y_distances**2 + z_distances**2)
        if bond_len <= 1.5 and bond_len > 0:
            real_bond_len = bond_len
            print(F'{molecule[i_1]} to {molecule[i_2]}:' , real_bond_len) 


['O' 'H1' 'H2']
[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]
3

O to H1: 0.9690005374652793
O to H2: 0.9690003348647513
H1 to O: 0.9690005374652793
H2 to O: 0.9690003348647513


In [322]:
# O to H1 and H1 to O refer to the same bond length. Remove the duplicates from your list.

# Modify your code to only print the atoms that are actually bonded to each other.
# We Use a distance cutoff of 1.5 angstroms to define a bond (that is, if the bond length is less/equal 
# to 1.5 angstroms, or greater than 0, then consider the atoms are bonded).

with open ('Bond_length' , "w+") as txt_file:
    
    import numpy
    import os

    xyz_file_path = os.path.join('CMS Workshp (MolSSI data)', 'water.xyz')
    xyz_file = numpy.genfromtxt(fname = xyz_file_path, skip_header=2,  dtype='unicode')  
    #print(xyz_file)     

    molecule = xyz_file[:,0]                           # These are our molecules (as string type)
    print(molecule)
    coordinates = xyz_file[:,1:]                       # These are our xyz coordinates (as string type)
    coordinates = coordinates.astype(numpy.float64)    # These are our xyz coordinates (as float type)
    print(coordinates)
# 1st column is x, 2nd column is y, 3rd column is z.
# now we will split the rows and assign i to each row
    row_num = len(coordinates[:,0])
    print(row_num)
    print('')
# 1st column is x_coordinates, 2nd column is y, 3rd column is z.
# 1st row is for O_atoms, 2nd for H1, and 3rd for H2
    
# It is the same if we use 3 instead of row_num (as row_num = 3), row_num generalizes the code.    
    for i_1 in range(0, row_num):          # So, values of i_1 = 0, 1 , 2 for 1st, 2nd & 3rd row
        for i_2 in range(0, row_num):      # So, values of i_2 = 0, 1 , 2 for 1st, 2nd & 3rd row
            if i_1 < i_2:            
                x_distances = coordinates[i_1,0] - coordinates[i_2,0]   # subtraction of 2 x values for 1st col
# i_1 / i_2 are just numbers varying from 0 1 2 (rows), this command will vary row from 1st-3rd for 1st col
                y_distances = coordinates[i_1,1] - coordinates[i_2,1]   
                z_distances = coordinates[i_1,2] - coordinates[i_2,2]
                bond_len = numpy.sqrt(x_distances**2 + y_distances**2 + z_distances**2)
                if bond_len <= 1.5 and bond_len > 0:
                    real_bond_len = bond_len
                    print(F'{molecule[i_1]} to {molecule[i_2]}:' , real_bond_len) 

# in this case, the if function avoids considering the same row. As i_1 and i_2 both vary from as 0 1 2
# e.g. when i_1 is 0, i_2 can only be 1 or 2 (but not 0).
# when i_1 is 1, i_2 can only be 2 (but not 0 and 1)

# Hence we are only left with three options, and for one of the options (H1-H2), the bond_len >1.5, so 
# only the following two are feasible.

# Now to print out the file in txt formate:

                    txt_file.write(F'{molecule[i_1]} to {molecule[i_2]}: real_bond_len \n')
txt_file.close()

['O' 'H1' 'H2']
[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]
3

O to H1: 0.9690005374652793
O to H2: 0.9690003348647513
